### ISSUE TITLE
"Trans 12 as" use LEDs

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/dexed#16]
Just like it is for Ratio/Fixed switch for operators:

![image](https://user-images.githubusercontent.com/2393720/74714858-b3b0c800-522b-11ea-9d1c-fb805c35b4b0.png)

Also we have enough room, maybe the parameter could be named more clearly and without any shorthands like "Transp".

**Comment by baconpaul** [comment]
this is in at head, so closing.
