### ISSUE TITLE
MPE mode with standard controller

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/dexed#46]
@baconpaul Dexed-Win64bit-1a290dc-20200311 | VST3i | Voice-Allocation Issues with MPE
 
Voice allocation issue with MPE active when using non-MPE MIDI controller.
 
To reproduce:
 
1. Load ED2-15
2. Hold a dyad of the 1/1 and fifth of ED2-15 in the bass on MIDI Notes: 45 and 54.
3. While sustaining the dyad, play chromatically up and down the scale over two octaves of ED2-15, starting on MIDI Note 60 and terminating on MIDI Note 90.
 
In the first half of the attached audio example demonstrating the behavior, MPE is disabled, while in the second half, MPE is activated.
 
As we can hear in the first section, the voices are rendered as expected, while in the second section with MPE active, voices are oddly overlaid.
 
[FYI: This sort of test, while the most basic musical scenario, will instantly reveal if there are any voice-allocation issues with virtual-instruments when working with microtonal tunings.]

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/dexed/blob/1a290dc63822b491d793b842aeb549cf56f59d14/Source/PluginProcessor.cpp#L497

**Comment by baconpaul** [comment]
I bet the bug is there when all the channels are the same and mpe is enabled it will find the wrong note.

**Comment by ghost** [comment]
FYI: In the above test, the non-MPE MIDI controller, and recorded MIDI data used in the audio documentation, was all transmitting on MIDI Channel 1.
