### ISSUE TITLE
Add LEDs to switches on PARM page

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/dexed#5]
To match the Monophonic button from the main GUI, so that it's easier to see at a glance which state is "on".

**Comment by baconpaul** [comment]
Rather than adding all those LEDs perhaps we should change the image so it is a lighted toggle

<img width="135" alt="Screen Shot 2020-02-17 at 6 46 42 PM" src="https://user-images.githubusercontent.com/13387561/74692605-0780ca00-51b6-11ea-94d5-2d977b713e1a.png">

Something kinda like that

**Comment by mkruselj** [comment]
I suppose this could be done in GUI redesign. However only the active position (in this case, right side of button) should have the glowing part on it.

**Comment by mkruselj** [comment]
This is actually done for a few commits now, so closing it.
